server:
  port: 8081


spring:
  datasource:
    username: root
    password: zhangyukang
    url: jdbc:mysql://127.0.0.1:3306/xinguan?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        login-username: zhangyukang
        login-password: zhangyukang
        allow:
        deny:
        url-pattern: /druid/*

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.coderman.api.*.pojo

